import './globals.css'
import { Inter } from 'next/font/google'
import React from "react";
import Link from "next/link";
import { btnStyle } from "@/styles";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <main className="min-h-screen p-6">
      <h1 className="pt-8 pl-8">
        <button className={`${btnStyle} px-4`}><Link href="/">Home</Link></button>
      </h1>
      {children}
    </main>
    </body>
    </html>
  )
}
