version: "3"
services:
  domain-mngr-webapp:
    image: docker.zdns.cn/gtld/test/domain-mngr-nginx:1.0.0
    container_name: domain-mngr-webapp
    restart: always
    networks:
      - gtld_apps_network
    environment:
      MO_AUTH_HEADER: "https://test-static.zdns.cn"
      MO_GATEWAY: "https://test-mo-gateway.zdns.cn"
      CLOUD_DPP_GATEWAY: "http://10.1.131.111:52020"
    volumes:
      - "./cert:/etc/nginx/cert"
      - "./conf.d/default.template:/etc/nginx/conf.d/default.template"
    ports:
      - "9996:80" #服务端口
      - "19996:443"
networks:
  gtld_apps_network:
    external: true
