#镜像构建
FROM docker.zdns.cn/gtld/node:latest as builder
WORKDIR /code
ENV NODE_OPTIONS=--openssl-legacy-provider

RUN yarn config set registry https://registry.npm.taobao.org && npm config set registry https://registry.npm.taobao.org && yarn config get registry
# 单独分离 package.json，是为了安装依赖可最大限度利用缓存
#ADD package.json yarn.lock /code/
ADD package.json /code/
RUN yarn

ADD . /code

#RUN yarn build

FROM docker.zdns.cn/gtld/node:latest
RUN mkdir /usr/local/apps
WORKDIR /usr/local/apps
ARG APP_VERSION=1.0.0
ARG APP_DIR=/usr/local/apps

COPY --from=builder /code ${APP_DIR}

ENTRYPOINT ["sh","-c","yarn dev"]

#镜像构建指令
#docker build -t docker.zdns.cn/gtld/test/domain-mngr-dev:latest -f docker/Dockerfile.dev .
